config/routes.rb
Rails.application.routes.draw do


  #devise_for :customers
  #devise_for :admins

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

 namespace :admin do
    get "/" => "homes#top"
    get "item/search" => "items#search"
    resources :order_details,only: [:update]
    resources :orders,only: [:show,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update] do

    end
  end


  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get "item/search" => "items#search"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "customers/show" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    patch 'customers/unsubscribe' => "customers#unsubscribe"
    get 'customers/withdraw' => "customers#withdraw"
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_active == false
      "退会"
    else
      "有効"
    end
  end

  #退会したユーザーがログインできないようにする
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :genre


  def self.search_for(content, method)
    if method == 'perfect'
      Item.where(title: content)
    elsif method == 'forward'
      Item.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Item.where('title LIKE ?', '%' + content)
    else
      Item.where('title LIKE ?', '%' + content + '%')
    end
  end
  has_one_attached :image
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize: "#{width}x#{height}!").processed
  end
  
  def with_tax_price
   (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
 has_many :order_details, dependent: :destroy
 belongs_to :customer

 #enumの定義　支払い方法、注文ステータス
 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, confirmation: 1, creationg: 2, preparing: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  #enumの定義　製造ステータス
  enum making_status: { fuka: 0, mati: 1, making: 2, complete: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!

  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end

  def search
    if params[:name].present?
      @items = Item.where('name LIKE ?', "%#{params[:name]}%")
    else
      @items = Item.none
    end
  end
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :is_active, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
    @selected_status = @order.status
    @order_detail = @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.status = params[:status]
    @order.update(order_params)
      if @order.status == "confirmation"
        @order_details.update_all(making_status: "mati")
      end
      redirect_to request.referer
  end
  
  private
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="m-5">注文履歴詳細</h4>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer_id) do %>
            <%= @order.customer.last_name %><%= @order.customer.first_name %>
            <%end%>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code %> <%=@order.address %><br>
              <%= @order.name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
            <%= f.select :status, options_for_select([["入金待ち",:waiting],["入金確認",:confirmation],["製作中",:creationg],["発送準備中",:preparing],["発送済み",:delivered]], selected: @selected_status) %>
            <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-9">
      <table>
        <thead class="table table-secondary">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <% total_amount = 0 %>
        <% @order_detail.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= (order_detail.price*1.1).round%></td>
          <td><%= order_detail.amount %></td>
          <td><%= (order_detail.price*1.1*order_detail.amount).floor %></td>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
            <%= f.select :making_status, options_for_select([["製作不可",:fuka],["製作待ち",:mati],["製作中",:making],["製作完了",:complete]], order_detail.making_status) %>
            <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= (@order.total_payment*1.1).floor - @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= (@order.total_payment*1.1).floor %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>