config/routes.rb
Rails.application.routes.draw do


  #devise_for :customers
  #devise_for :admins

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

 namespace :admin do
    get "/" => "homes#top"
    get "item/search" => "items#search"
    resources :order_details,only: [:update]
    resources :orders,only: [:show,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update] do

    end
  end


  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get "item/search" => "items#search"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "customers/show" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    patch 'customers/unsubscribe' => "customers#unsubscribe"
    get 'customers/withdraw' => "customers#withdraw"
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_active == false
      "退会"
    else
      "有効"
    end
  end

  #退会したユーザーがログインできないようにする
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :genre


  def self.search_for(content, method)
    if method == 'perfect'
      Item.where(title: content)
    elsif method == 'forward'
      Item.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Item.where('title LIKE ?', '%' + content)
    else
      Item.where('title LIKE ?', '%' + content + '%')
    end
  end
  has_one_attached :image
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize: "#{width}x#{height}!").processed
  end
  
  def with_tax_price
   (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
 has_many :order_details, dependent: :destroy
 belongs_to :customer

 #enumの定義　支払い方法、注文ステータス
 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, confirmation: 1, creationg: 2, preparing: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  #enumの定義　製造ステータス
  enum making_status: { fuka: 0, mati: 1, making: 2, complete: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!

  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end

  def search
    if params[:name].present?
      @items = Item.where('name LIKE ?', "%#{params[:name]}%")
    else
      @items = Item.none
    end
  end
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :is_active, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="m-5">ジャンル編集</h4>
      <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch do |f| %>
      <td>ジャンル名</td>
      <td><%= f.text_field :name %></td>
      <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
      <%end%>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <dev class="row">
    <dev class="col">
      <h4 class="m-5">ジャンル一覧・追加</h4>
      <%= form_with model:@genre, url: admin_genres_path do |f| %>
      <td>ジャンル名</td>
      <td><%= f.text_field :name %></td>
      <td><%= f.submit "新規登録", class:"btn btn-success" %></td>
      <%end%>
    </dev>
  </dev>
</div>

<div class="container">
  <dev class="row">
    <div class="col">
      <table class="table table-hover mt-5">
        <tr>
          <th class="table-secondary" colspan="2">ジャンル</th>
        </tr>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success" %></td>
        </tr>
        <%end%>
      </table>
    </div>
  </dev>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h3>商品編集</h3>
  </div>
  <div class="row">
   <div class="col-3" >
    </div>
    <div class="col-6">
      <%= form_with model:@item,url:admin_item_path, method: :patch do |f| %>
        <table>
          <tbody>
              <tr>
               <td>商品画像</td>
               <td>
                 <%= f.file_field :image, accept: "image/*" %>
               </td>
              </tr>
              <tr>
               <td>商品名</td>
               <td>
                 <%= f.text_field :name, rows:'3', placeholder: "商品名" %>
               </td>
              </tr>
              <tr>
               <td>商品説明</td>
               <td>
                   <%= f.text_area :introduction, rows:'6', placeholder: "商品説明"  %>
               </td>
              </tr>
              <tr>
                <td>ジャンル</td>
              <td>
                 <%= f.collection_select(:genre_id, Genre.all, :id, :name) %>
              </td>
              </tr>
              <tr>
                <td>税抜価格</td>
                <td>
                  <%= f.number_field :price, rows:'3', placeholder: "1000" %>
                </td>
              </tr>
              <tr>
                <td>販売ステータス</td>
                <td>
                  <p><%= f.radio_button :is_active, :true %>販売中</p>
                  <p><%= f.radio_button :is_active, :false %>販売停止中</p>
                </td>
              </tr>
              <tr>
                <td>
                <%= f.submit "変更を保存",class: "btn btn-success" %>
                </td>
              </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="m-3">商品一覧</h4>
    </div>
    <!--商品新規登録ボタン-->
    <div class="col text-right m-3">
      <%= link_to "+", new_admin_item_path, class:"btn btn-success" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-hover">
        <thead>
          <tr class="table-secondary">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name,admin_item_path(item.id) %></td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <td><span style="color:green;"><%= item.is_active? ? '販売中' : '販売停止中' %></td>
          </tr>
         <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h3>商品新規登録</h3>
  </div>
  <div class="row">
   <div class="col-3" >
    </div>
    <div class="col-6">
      <%= form_with model:@item,url:admin_items_path do |f| %>
        <table>
          <tbody>
              <tr>
              　<td>商品画像</td>
              　<td>
              　  <%= f.file_field :image, accept: "image/*" %>
              　</td>
              </tr>
              <tr>
              　<td>商品名</td>
              　<td>
              　  <%= f.text_field :name, rows:'3', placeholder: "商品名" %>
              　</td>
              </tr>
              <tr>
              　<td>商品説明</td>
              　<td>
              　    <%= f.text_area :introduction, rows:'6', placeholder: "商品説明"  %>
              　</td>
              </tr>
              <tr>
                <td>ジャンル</td>
            　　<td>
            　　   <%= f.collection_select(:genre_id, Genre.all, :id, :name) %>
            　　</td>
              </tr>
              <tr>
                <td>税抜価格</td>
                <td>
                  <%= f.number_field :price, rows:'3', placeholder: "1000" %>
                </td>
              </tr>
              <tr>
                <td>販売ステータス</td>
                <td>
                  <p><%= f.radio_button :is_active, :true %>販売中</p>
                  <p><%= f.radio_button :is_active, :false %>販売停止中</p>
                </td>
              </tr>
              <tr>
                <td>
                <%= f.submit '新規登録',class: "btn btn-success" %>
                </td>
              </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/admin/items/search.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>商品検索結果</h1>
      <h2>(全<%= @items.count %>件)</h2>
      <% if [] != @items %>
      <table class="table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name,admin_item_path(item.id) %></td>
            <td><%= item.price %></td>
            <td><%= item.genre_id %></td>
            <td><span style="color:green;"><%= item.is_active? ? '販売中' : '販売停止中' %></td>
          </tr>
         <% end %>
        </tbody>
      </table>
      <% else %>
      <h1 class= text-center>0件でした。</h1>
      <% end %>
     </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2 class="text-center my-5">商品詳細</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div style="padding-left:20%;">
        <%= image_tag @item.get_image(300,300) %>
      </div>
    </div>
    <div class="col-md-6">
      <p class="my-4"><strong>商品名 </strong><span style="margin-left:150px;"><%= @item.name %></span></p>
      <p class="my-4"><strong>商品説明 </strong><span style="margin-left:135px;"><%= @item.introduction %></span></p><!-- descriptionをintroductionに変更-->
      <p class="my-4"><strong>税込価格（税抜価格） </strong><span style="margin-left:40px;"><%= number_with_delimiter((@item.price * 1.1).round) %>円 ( <%= number_with_delimiter(@item.price) %>円 )</span></p>
      <p class="my-4"><strong>販売ステータス </strong><span style="margin-left:90px; color:green;"><%= @item.is_active? ? '販売中' : '販売停止中' %></span></p><!-- on_saleをis_activeに変更-->
      <%= link_to '編集する', edit_admin_item_path(@item), class: 'btn btn-success' %>
    </div>
  </div>
</div>