config/routes.rb
Rails.application.routes.draw do


  #devise_for :customers
  #devise_for :admins

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

 namespace :admin do
    get "/" => "homes#top"
    get "item/search" => "items#search"
    resources :order_details,only: [:update]
    resources :orders,only: [:show,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update] do

    end
  end


  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get "item/search" => "items#search"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "customers/show" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    patch 'customers/unsubscribe' => "customers#unsubscribe"
    get 'customers/withdraw' => "customers#withdraw"
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_active == false
      "退会"
    else
      "有効"
    end
  end

  #退会したユーザーがログインできないようにする
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :genre


  def self.search_for(content, method)
    if method == 'perfect'
      Item.where(title: content)
    elsif method == 'forward'
      Item.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Item.where('title LIKE ?', '%' + content)
    else
      Item.where('title LIKE ?', '%' + content + '%')
    end
  end
  has_one_attached :image
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize: "#{width}x#{height}!").processed
  end
  
  def with_tax_price
   (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
 has_many :order_details, dependent: :destroy
 belongs_to :customer

 #enumの定義　支払い方法、注文ステータス
 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, confirmation: 1, creationg: 2, preparing: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  #enumの定義　製造ステータス
  enum making_status: { fuka: 0, mati: 1, making: 2, complete: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!

  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">

            <a class="navbar-brand" href="/">
               <span>LOGO</span>
            </a>
              <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>


              <div class="collapse navbar-collapse" id="navbarNavDropdown">


                <ul class="navbar-nav ml-auto">
               <% if customer_signed_in? %>
               <li class="mr-5 nav-link text-light">ようこそ、<%= current_customer.last_name %>さん！</li>
                       <li class="ml-5">
                         <%= link_to customers_show_path, class:"nav-link text-light" do %>
                           <i class="fa-solid fa-house"></i> マイページ
                         <% end %>
                       </li>
                       <li >
                         <%= link_to items_path, class:"nav-link text-light" do %>
                           <i class="fa-solid fa-book-open"></i> 商品一覧
                         <% end %>
                       </li>
                       <li>
                         <%= link_to cart_items_path, class:"nav-link text-light" do %>
                           <i class="fa-solid fa-book-open"></i> カート
                         <% end %>
                       </li>
                       <li>
                         <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link text-light" do %>
                           <i class="fa-solid fa-sign-out-alt"></i> ログアウト
                         <% end %>

                       </li>
                       <p id="notice"><%= notice %></p>
                      <div class="d-flex justify-content-center mb-2">
                        <%= form_with url: item_search_path, method: :get, local: true do |f| %>
                            <%= f.text_field :name %>
                            <%= f.submit :search %>
                        <% end %>
                      </div>
                     <% elsif admin_signed_in? %>
                               <li>
                                 <%= link_to admin_items_path, class:"nav-link text-light" do %>
                                   <i class="fa-solid fa-link"></i> 商品一覧
                                 <% end %>
                               </li>
                               <li>
                                 <%= link_to admin_customers_path, class:"nav-link text-light" do %>
                                   <i class="fa-solid fa-link"></i> 会員一覧
                                 <% end %>
                               </li>
                               <li>
                                 <%= link_to admin_path, class:"nav-link text-light" do %>
                                   <i class="fa-solid fa-link"></i> 注文履歴一覧
                                 <% end %>
                               </li>
                               <li>
                                 <%= link_to admin_genres_path, class:"nav-link text-light" do %>
                                   <i class="fa-solid fa-link"></i> ジャンル一覧
                                 <% end %>
                               </li>
                               <li>
                                 <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-light" do %>
                                   <i class="fa-solid fa-sign-out-alt"></i> ログアウト
                                 <% end %>
                               </li>
                                     <p id="notice"><%= notice %></p>
                                  <div class="d-flex justify-content-center mb-2">
                                    <%= form_with url:  admin_item_search_path, method: :get, local: true do |f| %>
                                        <%= f.text_field :name %>
                                        <%= f.submit :search %>
                                    <% end %>
                                  </div>

                             <% else %>
                                   <li>
                                     <%= link_to about_path, class:"nav-link text-light" do %>
                                       <i class="fa-solid fa-link"></i> About
                                     <% end %>
                                   </li>
                                   <li>
                                     <%= link_to items_path, class:"nav-link text-light" do %>
                                       <i class="fa-solid fa-book-open"></i> 商品一覧
                                     <% end %>
                                   </li>
                                   <li>
                                     <%= link_to new_customer_registration_path, class:"nav-link text-light" do %>
                                       <i class="fa-solid fa-user-plus"></i> 新規登録
                                     <% end %>
                                   </li>
                                   <li>
                                     <%= link_to new_customer_session_path, class:"nav-link text-light" do %>
                                       <i class="fa-solid fa-sign-in-alt"></i> ログイン
                                     <% end %>
                                   </li>
                              <% end %>
                </ul>
              </div>
          </div>
      </nav>
    </header>
    <%= yield %>
    <footer>

    </footer>
  </body>
</html>